name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ftp.cgcapps.cl
          username: ${[ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          local-dir: ./dist
